{
    "name": "Tourism Provider Portal",
    "version": "18.0.1.0.0",
    "summary": "WhatsApp-first onboarding and portal for tourism providers",
    "category": "Website",
    "author": "Your Company",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "contacts",
        "crm",
        "portal",
        "website",
        "auth_signup",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/res_partner_views.xml",
        "views/tourism_post_views.xml",
        "views/tourism_menus.xml",
        "views/website_templates.xml",
    ],
    "installable": True,
    "application": True,
}
